[package]
name = "monitor-providers"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
monitor-core.workspace = true
monitor-integrations.workspace = true
async-trait.workspace = true
chrono.workspace = true
futures.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
url.workspace = true
google-cloud-auth = { version = "*", default-features = false, features = ["default-rustls-provider"] }
google-cloud-monitoring-v3 = "*"
google-cloud-asset-v1 = "*"
aws-config = { version = "*", default-features = false, features = ["default-https-client", "rt-tokio", "sso", "credentials-process"] }
aws-sdk-cloudwatch = { version = "*", default-features = false, features = ["rt-tokio", "default-https-client"] }
aws-sdk-sts = { version = "*", default-features = false, features = ["rt-tokio", "default-https-client"] }
aws-credential-types = "*"
aws-sigv4 = "*"
aws-smithy-runtime-api = "*"
azure_identity = { version = "*", default-features = false, features = ["tokio"] }
azure_core = { version = "*", default-features = false, features = ["reqwest_rustls", "tokio"] }

[lints]
workspace = true
