//! Sparse per-scope settings overlays.
use super::duration::Span;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SettingsPatch {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub log_dedup_entries: Option<usize>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub log_overlap: Option<Span>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub certificate_warning: Option<Span>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub recovery_age_error: Option<Option<Span>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub interval: Option<Span>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub samples: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sample_interval: Option<Span>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub connect_timeout: Option<Span>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub attempt_timeout: Option<Span>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub operation_timeout: Option<Span>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub attempts: Option<usize>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub concurrency: Option<usize>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scope_concurrency: Option<usize>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub subprocesses: Option<usize>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ready_queue: Option<usize>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub jitter_percent: Option<u8>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_assets: Option<usize>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_findings: Option<usize>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub memory_bytes: Option<usize>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub response_bytes: Option<usize>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_pages: Option<usize>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub page_size: Option<usize>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_series: Option<usize>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub log_window: Option<Span>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub log_entries: Option<usize>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub runtime_window: Option<Span>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub runtime_entries: Option<usize>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metric_window: Option<Span>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub history_interval: Option<Span>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub history_age: Option<Span>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub history_count: Option<usize>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub history_bytes: Option<u64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub node_grace: Option<Span>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rollout_grace: Option<Span>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub capacity_warning: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub capacity_error: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub capacity_sustain: Option<Span>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub recover_confirmations: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub removal_confirmations: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub stale_after: Option<Option<Span>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub queue_age_error: Option<Option<f64>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub latency_error_ms: Option<Option<f64>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub required: Option<bool>,
}
