[package]
name = "healthcheck-monitor"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
monitor-core.workspace = true
monitor-integrations.workspace = true
monitor-providers.workspace = true
chrono.workspace = true
clap.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber = { version = "*", default-features = false, features = ["json", "env-filter", "fmt", "time"] }
tikv-jemallocator = { version = "*", default-features = false, features = ["background_threads", "unprefixed_malloc_on_supported_platforms"] }

[lints]
workspace = true
