//! Native cloud monitoring adapters.
mod advertisements;
pub mod auth;
pub mod aws;
pub mod aws_alarms;
mod aws_catalog;
mod aws_clients;
mod aws_details;
mod aws_errors;
pub mod aws_logs;
mod aws_metric_discovery;
pub mod aws_metrics;
mod aws_projection;
pub mod aws_slo;
#[cfg(test)]
mod aws_tests;
pub mod aws_transport;
pub mod azure;
mod azure_details;
pub mod azure_logs;
mod azure_metric_discovery;
pub mod azure_metrics;
mod azure_projection;
mod cloud_logs;
pub mod common;
pub mod details;
pub mod discovery;
mod endpoint_scan;
pub mod gcp;
mod gcp_catalog;
pub mod gcp_logs;
pub mod gcp_slo;
pub mod inventory_cache;
mod log_cursor;
pub mod metric_catalog;
pub mod metric_window;
pub mod metrics;
mod projection_rows;
mod quotas;
pub mod resource_projection;
pub mod router;
mod routing;
mod routing_edge;
mod slo_projection;
