//! Native cloud monitoring adapters.
mod advertisements;
mod artifact_projection;
pub mod auth;
mod auth_identity;
pub mod aws;
pub mod aws_alarms;
mod aws_batches;
mod aws_catalog;
mod aws_clients;
mod aws_credential_cache;
mod aws_credential_process;
mod aws_details;
mod aws_errors;
pub mod aws_logs;
pub mod aws_metric_batch;
mod aws_metric_discovery;
mod aws_metric_inventory;
mod aws_metric_plan;
pub mod aws_metrics;
mod aws_native;
mod aws_native_compute;
mod aws_native_databases;
mod aws_native_ecs;
mod aws_native_edge;
mod aws_native_governance;
mod aws_native_lambda;
mod aws_native_logs;
mod aws_native_queues;
mod aws_native_release;
mod aws_native_security;
mod aws_native_storage;
#[cfg(test)]
mod aws_native_tests;
mod aws_pipeline;
mod aws_process_chain;
mod aws_process_profiles;
#[cfg(test)]
mod aws_process_tests;
mod aws_projection;
pub mod aws_slo;
#[cfg(test)]
mod aws_tests;
pub mod aws_transport;
pub mod azure;
pub mod azure_activity;
mod azure_auth;
mod azure_details;
pub mod azure_logs;
mod azure_metric_discovery;
pub mod azure_metrics;
mod azure_operational;
mod azure_projection;
pub mod azure_registry;
mod azure_registry_auth;
mod cloud_logs;
pub mod common;
mod common_parallel;
pub mod details;
pub mod discovery;
mod endpoint;
mod endpoint_scan;
pub mod gcp;
mod gcp_catalog;
pub mod gcp_logs;
mod gcp_metric_pages;
pub mod gcp_metrics;
mod gcp_operational;
pub mod gcp_slo;
mod google_credentials;
#[cfg(test)]
mod identity_tests;
pub mod inventory_cache;
mod key_vault;
mod log_cursor;
mod metadata_fields;
pub mod metric_catalog;
pub mod metric_identity;
pub mod metric_window;
pub mod metrics;
mod pagination;
mod projection_rows;
mod quotas;
mod registry_manifests;
#[cfg(test)]
mod registry_token_tests;
mod registry_tokens;
mod registry_transport;
pub mod resource_projection;
mod resource_scope;
pub mod router;
mod routing;
mod routing_discovery;
mod routing_edge;
mod routing_github;
mod runtime_images;
mod scan_budget;
mod slo_projection;
